language: php

php: [5.4, 5.5, 5.6]

branches:
  except:
    - /^bugfix\/.*$/
    - /^feature\/.*$/
    - /^optimization\/.*$/

before_script:
  - composer install --prefer-source --no-interaction --no-progress
  - export PATH=./bin:$PATH

script:
  - phpspec run -f pretty --no-interaction
  - behat --strict